config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  devise_for :users
  get 'search' => 'search#index', as: 'search'
  resources :questions do
    resources :answers
  end
  scope :users do
    get 'questions' => 'questions#user', as: 'questions_user'
    get 'answers' => 'answers#user', as: 'answers_user'
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    alias_action :user, :show, :edit, :update, :destroy, to: :rud
    alias_action :new, :create, to: :created

    user ||= User.new # guest user (not logged in)
    if user.persisted?
      can :rud, Answer, user_id: user.id
      can :rud, Question, user_id: user.id
      can :created, [Question, Answer]
      can :read, :all
    else
      can :index, :all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  include Interest

  validates :content, presence: true
  validates :content, length: { in: 10..500 }
  validates :interest, numericality: { only_integer: true }

  belongs_to :question
  belongs_to :user
end

app/models/concerns/interest.rb
module Interest
  def update_interest(vote)
    self.interest += vote
    self.save
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  default_scope { includes(:answers) }
  scope :user_answers, -> (user_id) { joins(:answers).where('answers.user_id = ?', user_id) }
  scope :user_questions, -> (user_id) { where('user_id = ?', user_id) }

  include Interest

  validates :title,
            :content,
            presence: true
  validates :title, length: { in: 10..100 }
  validates :content, length: { in: 10..500 }
  validates :view,
            :interest,
            numericality: { only_integer: true }
  validates :active, inclusion: { in: [true, false] }

  belongs_to :user
  has_many :answers
  has_many :user_view_question

  searchable do
    text :title, :content
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_view_question.rb
class UserViewQuestion < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :user_id, uniqueness: { scope: :question_id}, presence: true

  def self.add_view(question, user)
    v = self.new
    v.question = question
    v.user = user
    v.save
  end
end

app/controllers/answers_controller.rb
require 'pp'
class AnswersController < ApplicationController

  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  authorize_resource
  before_action :set_question, except: [:user]

  def user
    @questions = Question.user_answers current_user.id
  end

  # GET /answers
  # GET /answers.json
  def index
    UserViewQuestion.add_view @question, current_user if user_signed_in?
    pp @question.user_view_question.count
    @answers = @question.answers
    @answer = Answer.new
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to question_answers_path(@question), notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { redirect_to question_answers_path(@question), alert: 'Answer was not created.' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answers_user_path, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_user_path, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_question
      @question = Question.find(params[:question_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params[:answer].permit(:content, :question_id, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    path = user_signed_in? ? root_path : new_user_session_path
    redirect_to path, alert: exception.message
  end
end

app/controllers/questions_controller.rb
require 'pp'
class QuestionsController < ApplicationController

  before_action :set_question, only: [:show, :edit, :update, :destroy]
  authorize_resource

  def user
    @questions = Question.user_questions current_user.id
  end

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to question_answers_path(@question), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_user_path, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_user_path, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :view, :interest, :active, :user_id)
    end
end

app/controllers/search_controller.rb
require 'pp'
class SearchController < ApplicationController
  def index
    @search = {}
    @search[:results] = []
    render if (@search[:request] = params[:search]).empty?
    @search[:results] = Question.search do
      fulltext params[:search] do
        phrase_fields title: 2.0
        query_phrase_slop 100
      end
    end.results
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, placeholder: 'Content' %>
  </div>
  <div class="field">
    <%= f.hidden_field :question_id, value: @question.id %>
    <%= f.hidden_field :user_id, value: current_user ? current_user.id : 0 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>
<%= link_to "Delete Answer", question_answer_path(@question, @answer), method: :delete, class: "button delete", confirm: "Are you sure ?" %>

<%= link_to 'Back', answers_user_path, class: 'button' %>

app/views/answers/index.html.erb
<section id='detail' class=''>
  <div id="question" class='row'>
    <div class='col-xs-12'>
      <h1><%= @question.title %></h1>
    </div>
    <div class='col-xs-10'>
      <p><%= @question.content %></p>
      <div class="more">
        <span class='time'>Created: <%= @question.updated_at %></span> 
        <span class='time'>Last update: <%= @question.updated_at %></span> 
      </div>
    </div>
    <div class="info col-xs-2">
      <div>
        <i class="fa fa-star"></i><%= @question.interest %>
      </div>
      <div>
        <i class="fa fa-eye"></i><%= @question.user_view_question.count %>
      </div>
      <div>
        <% if @question.active %>
          <i class="fa fa-unlock-alt"></i>
        <% else %>
          <i class="fa fa-lock"></i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="group">
    <h2><%= @answers.size %> Answer(s)</h2>
  </div>
  <div id="answer">
    <% @answers.each do |answer| %>
    <div class="answer clearfix <%= cycle("odd", "even") %>">
      <div class='content col-xs-10'>
        <%= answer.content %>
        <div class="more">
          <span class='time'>Created: <%= answer.updated_at %></span> 
          <span class='time'>Last update: <%= answer.updated_at %></span> 
        </div>
      </div>
      <div class="info col-xs-2">
        <div>
          <i class="fa fa-star"></i><%= answer.interest %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="group">
    <h2>Your answer</h2>
  </div>
  <%= render 'form' %>
</section>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', question_answers_path(@question) %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_question_answer_path(@question, @answer) %> |
<%= link_to 'Back', question_answers_path(@question) %>

app/views/answers/user.html.erb
<h1>User answers</h1>
<% @questions.each do |question| %>
  <%=
    render 'shared/listing_answers',
    question: question,
    answers: question.answers
  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Why</title>
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/nav' %>
  <%= render 'shared/search_box' %>
  <div class="flash">
    <p class="notice  <%= 'hide' unless notice %>"><%= notice %></p>
    <p class="alert  <%= 'hide' unless alert %>"><%= alert %></p>
  </div>
  <%= yield %>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :title, placeholder: 'Title' %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: 'Content' %>
  </div>
  <div class="field">
    <%= f.hidden_field :interest, value: 0 %>
    <%= f.hidden_field :active, value: true %>
    <%= f.hidden_field :view, value: 0 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>
<%=link_to "Delete Question", question_path(@question), method: :delete, class: "button delete", :confirm => "Are you sure ?"%>
<%= link_to 'Back', questions_user_path, class: 'button' %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<%= render 'shared/listing_question', questions: @questions %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<% link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/questions/user.html.erb
<h1>User questions</h1>

<%= render 'shared/listing_question_user', questions: @questions %>

app/views/search/index.html.erb
<h1><%= @search[:results].size %> results for : <%= @search[:request] %></h1>
<%= render 'shared/listing_question', questions: @search[:results] %>

app/views/shared/_listing_answers.html.erb
<section id='detail' class=''>
  <div id="question" class='row'>
    <div class='col-xs-12'>
      <h1><%= question.title %></h1>
    </div>
    <div class='col-xs-10'>
      <p><%= question.content %></p>
      <div class="more">
        <span class='time'>Created: <%= question.updated_at %></span> 
        <span class='time'>Last update: <%= question.updated_at %></span> 
      </div>
    </div>
    <div class="info col-xs-2">
      <div>
        <i class="fa fa-star"></i><%= question.interest %>
      </div>
      <div>
        <i class="fa fa-eye"></i><%= question.user_view_question.count %>
      </div>
      <div>
        <% if question.active %>
          <i class="fa fa-unlock-alt"></i>
        <% else %>
          <i class="fa fa-lock"></i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="group">
    <h2><%= answers.size %> Answer(s)</h2>
  </div>
  <div id="answer">
    <% answers.each do |answer| %>
    <div class="answer clearfix <%= cycle("odd", "even") %>">
      <div class='content col-xs-10'>
        <%= link_to answer.content, edit_question_answer_path(question, answer) %>
        <div class="more">
          <span class='time'>Created: <%= answer.updated_at %></span> 
          <span class='time'>Last update: <%= answer.updated_at %></span> 
        </div>
      </div>
      <div class="info col-xs-2">
        <div>
          <i class="fa fa-star"></i><%= answer.interest %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>

app/views/shared/_listing_question.html.erb
<div class="listing">
  <div class="head clearfix">
    <ul class='row'>
      <li class='col-xs-1 col-sm-2'><i class="fa fa-star"></i>vote</li>
      <li class='col-xs-1 col-sm-2'><i class="fa fa-lightbulb-o"></i>Answer</li>
      <li class='col-xs-1 col-sm-2'><i class="fa fa-eye"></i>View</li>
      <li class='col-xs-8 col-sm-5'><i class="fa fa-font"></i>Title</li>
      <li class='col-xs-1 col-sm-1'><i class="fa fa-lock"></i></li>
    </ul>
  </div>
  <div class="body">
    <% questions.each do |question| %>
    <ul class='row <%= cycle("odd", "even") %>'>
      <li class='col-xs-1 col-sm-2'><%= question.interest %></li>
      <li class='col-xs-1 col-sm-2'><%= question.answers.size %></li>
      <li class='col-xs-1 col-sm-2'><%= question.user_view_question.count %></li>
      <li class='col-xs-8 col-sm-5'>
        <p><%= link_to truncate(question.title, length: 50, omission: '...'), question_answers_path(question) %></p>
        <p><%= link_to truncate(question.content, length: 100, omission: '...'), question_answers_path(question) %></p>
        <span class='time'>Last update: <%= question.updated_at %></span>
      </li>
      <li class='col-xs-1 col-sm-1'>
        <% if question.active %>
          <i class="fa fa-unlock"></i>
        <% else %>
          <i class="fa fa-lock"></i>
        <% end %>
      </li>
    </ul>
    <% end %>
  </div>
</div>

app/views/shared/_listing_question_user.html.erb
<div class="listing">
  <div class="head clearfix">
    <ul class='row'>
      <li class='col-xs-1 col-sm-2'><i class="fa fa-star"></i>vote</li>
      <li class='col-xs-1 col-sm-2'><i class="fa fa-lightbulb-o"></i>Answer</li>
      <li class='col-xs-1 col-sm-2'><i class="fa fa-eye"></i>View</li>
      <li class='col-xs-8 col-sm-5'><i class="fa fa-font"></i>Title</li>
      <li class='col-xs-1 col-sm-1'><i class="fa fa-lock"></i></li>
    </ul>
  </div>
  <div class="body">
    <% questions.each do |question| %>
    <ul class='row <%= cycle("odd", "even") %>'>
      <li class='col-xs-1 col-sm-2'><%= question.interest %></li>
      <li class='col-xs-1 col-sm-2'><%= question.answers.size %></li>
      <li class='col-xs-1 col-sm-2'><%= question.view %></li>
      <li class='col-xs-8 col-sm-5'>
        <p><%= link_to truncate(question.title, length: 50, omission: '...'), edit_question_path(question) %></p>
        <p><%= link_to truncate(question.content, length: 100, omission: '...'), edit_question_path(question) %></p>
        <span class='time'>Last update: <%= question.updated_at %></span>
      </li>
      <li class='col-xs-1 col-sm-1'>
        <% if question.active %>
          <i class="fa fa-unlock"></i>
        <% else %>
          <i class="fa fa-lock"></i>
        <% end %>
      </li>
    </ul>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<header class='main-header clearfix'>
<div class="navbar wrapper">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h1 class='header-title'>
        <i class="fa fa-rocket"></i>
        <%= link_to 'Why', root_path %>
      </h1>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Ask Question', new_question_path %>
        </li>
        <%= render "shared/user_#{user_signed_in?}" %>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_search_box.html.erb
<%= form_tag(search_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, nil, placeholder: "Search question or answer" %>
<% end %>

app/views/shared/_user_false.html.erb
<li class="item">
  <%= link_to 'Questions', questions_path %>
</li>
<li class='item'>
  <%= link_to 'Sign in', new_user_session_path %> 
</li>
<li class='item'>
  <%= link_to 'Sign up', new_user_registration_path %> 
</li>

app/views/shared/_user_true.html.erb
<li class="item">
  <%= link_to 'Questions', questions_path %>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">My account</a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to questions_user_path  do %>
       my questions<i class="fa fa-question"></i>
      <% end %>
    </li>
    <li>
      <%= link_to answers_user_path do %>
        my answers<i class="fa fa-lightbulb-o"></i>
      <% end %>
    </li>
    <li>
      <%= link_to edit_user_registration_path do %>
        profile<i class="fa fa-user"></i>
      <% end %>
    </li>
    <li class="divider"></li>
    <li class='item'>
      <%= link_to destroy_user_session_path, method: 'delete' do %>
        Sign out<i class="fa fa-sign-out"></i>
      <% end %> 
    </li>
  </ul>
</li>